### ISSUE TITLE
an issue with ( https://4url.ml/api/short/ )

### ISSUE THREAD

**Issue by E3saR33** [azizmjaber02/forurl#2]
> links are redirecting to `youtube.com` and its shortCode will be `UZvD6A9`

> as example : 
_ https://4url.ml/api/short?url=https://google.com/
_ https://4url.ml/api/short?url=https://twitter.com/
_ https://4url.ml/api/short?url=https://facebook.com/
_ https://4url.ml/api/short?url=https://wikipedia.com/

**Comment by azizmjaber02** [comment]
**the problem from repl.it the website hosting ...**
i think i will publish the source code and cancel the project ...
:] thx u any why

[4url on repl.it](https://4url.azizjaber.repl.co)

**Comment by E3saR33** [comment]
I just wanted to tell you about this issue .
